const htmlPdf = require('html-pdf-node');

// Function to generate PDF from a specific trip
exports.generateTripPDF = async (userData, trip) => {
  try {
    // Extract trip details
    const { cityName, dates, activities } = trip;
    
    // Format the dates for display
    const formattedDates = dates.map(date => formatDate(date));
    const dateRange = dates.length > 1 
      ? `${formattedDates[0]} - ${formattedDates[dates.length-1]}` 
      : formattedDates[0];
    
    // Generate HTML content for the PDF
    const htmlContent = `
      <html>
        <head>
          <style>
            body {
              font-family: Arial, sans-serif;
              color: #333;
              line-height: 1.6;
              margin: 0;
              padding: 20px;
            }
            .header {
              text-align: center;
              margin-bottom: 30px;
              padding-bottom: 20px;
              border-bottom: 2px solid #f7aad0;
            }
            h1 {
              color: #db0589;
              font-size: 28px;
              margin-bottom: 10px;
            }
            h2 {
              color: #33658A;
              font-size: 22px;
              margin-top: 20px;
              margin-bottom: 10px;
            }
            h3 {
              color: #30D5C8;
              font-size: 18px;
              margin-top: 15px;
              margin-bottom: 5px;
              padding: 8px;
              background-color: #f1f1f1;
              border-radius: 4px;
            }
            .trip-details {
              margin-bottom: 30px;
              padding: 15px;
              background-color: #f9f9f9;
              border-radius: 5px;
              border-left: 4px solid #f7aad0;
            }
            .activities {
              margin-left: 20px;
            }
            .activity {
              margin-bottom: 10px;
              padding: 10px;
              border-bottom: 1px solid #eee;
            }
            .time {
              font-weight: bold;
              color: #33658A;
              display: inline-block;
              width: 100px;
            }
            .footer {
              text-align: center;
              margin-top: 50px;
              padding-top: 20px;
              border-top: 1px solid #eee;
              font-size: 12px;
              color: #999;
            }
            .no-activities {
              font-style: italic;
              color: #777;
              margin: 10px 0 10px 20px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Travel Itinerary: ${cityName}</h1>
            <p>Created for: ${userData.displayName || userData.username || userData.email}</p>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
          </div>
          
          <div class="trip-details">
            <h2>${cityName}</h2>
            <p>
              <strong>Dates:</strong> ${dateRange}
              (${dates.length} ${dates.length === 1 ? 'day' : 'days'})
            </p>
          </div>
          
          <div class="day-activities">
            ${dates.map(date => `
              <div class="day">
                <h3>${formatDate(date)}</h3>
                ${activities[date] && activities[date].length > 0 
                  ? `
                    <div class="activities">
                      ${activities[date].map(activity => `
                        <div class="activity">
                          <span class="time">${activity.time}</span> ${activity.description}
                        </div>
                      `).join('')}
                    </div>
                  ` 
                  : '<p class="no-activities">No activities scheduled for this day.</p>'
                }
              </div>
            `).join('')}
          </div>
          
          <div class="footer">
            <p>Generated by Alcove - Your Smart Travel Companion</p>
          </div>
        </body>
      </html>
    `;
    
    // Generate PDF from HTML
    const options = { format: 'A4' };
    const file = { content: htmlContent };
    
    const pdfBuffer = await htmlPdf.generatePdf(file, options);
    
    return pdfBuffer;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate trip PDF');
  }
};

// Helper function to format date
function formatDate(dateStr) {
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-US', { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
}